export { default as Dialog } from './Dialog.vue'
export { default as DialogContent } from './DialogContent.vue'
export { default as DialogDescription } from './DialogDescription.vue'
export { default as DialogOverlay } from './DialogOverlay.vue'
export { default as DialogTitle } from './DialogTitle.vue'
