version: '3.8'
services:
  nats:
    image: nats
  
  stan:
    image: nats-streaming

  jetstream:
    image: nats
    command: ["-js"]

  mongostore:
    image: mongo
    command: ["--quiet", "--logpath", "/dev/null", "--bind_ip_all"]

  mongostore_replicaset:
    image: mongo
    command: ["--quiet", "--logpath", "/dev/null", "--replSet", "rs0", "--bind_ip_all"]

  mongostore_replicaset_init:
    image: mongo
    entrypoint: /entrypoint.sh
    environment:
      REPLICA_HOST: mongostore_replicaset
    volumes:
      - "${PWD}/.docker/init-mongo.sh:/entrypoint.sh"
  
  mongosnap:
    image: mongo
    command: ["--quiet", "--logpath", "/dev/null", "--bind_ip_all"]

  mongotag_replicaset:
    image: mongo
    command: ["--quiet", "--logpath", "/dev/null", "--replSet", "rs0", "--bind_ip_all"]

  mongotag_init:
    image: mongo
    entrypoint: /entrypoint.sh
    environment:
      REPLICA_HOST: mongotag
    volumes:
      - "${PWD}/.docker/init-mongo.sh:/entrypoint.sh"

  test:
    depends_on:
      - nats
      - stan
      - jetstream
      - mongostore
      - mongostore_replicaset
      - mongostore_replicaset_init
      - mongosnap
      - mongotag_replicaset
      - mongotag_init
    build:
      context: ..
      dockerfile: .docker/coverage.Dockerfile
      args:
        TAGS: nats,mongostore,mongosnap,mongotag
    environment:
      - NATS_URL=nats://nats:4222
      - STAN_URL=nats://stan:4222
      - JETSTREAM_URL=nats://jetstream:4222
      - MONGOSTORE_URL=mongodb://mongostore:27017
      - MONGOREPLSTORE_URL=mongodb://mongostore_replicaset:27017
      - MONGOSNAP_URL=mongodb://mongosnap:27017
      - MONGOTAG_URL=mongodb://mongotag:27017
    volumes:
      - ../out:/coverage/out
