version: '3.8'
services:
  mongostore:
    image: mongo
    command: ["--quiet", "--logpath", "/dev/null", "--bind_ip_all"]

  mongostore_replicaset:
    image: mongo
    command: ["--quiet", "--logpath", "/dev/null", "--replSet", "rs0", "--bind_ip_all"]
  
  mongostore_replicaset_init:
    image: mongo
    entrypoint: /entrypoint.sh
    environment:
      REPLICA_HOST: mongostore_replicaset
    volumes:
      - "${PWD}/.docker/init-mongo.sh:/entrypoint.sh"
  
  mongosnap:
    image: mongo
    command: ["--quiet", "--logpath", "/dev/null", "--bind_ip_all"]

  mongomodel:
    image: mongo
    command: ["--quiet", "--logpath", "/dev/null", "--replSet", "rs0", "--bind_ip_all"]

  mongomodel_init:
    image: mongo
    entrypoint: /entrypoint.sh
    environment:
      REPLICA_HOST: mongomodel
    volumes:
      - "${PWD}/.docker/init-mongo.sh:/entrypoint.sh"

  test:
    depends_on:
      - mongostore
      - mongostore_replicaset
      - mongostore_replicaset_init
      - mongosnap
      - mongomodel
      - mongomodel_init
    build:
      context: ..
      dockerfile: .docker/tag-test.Dockerfile
      args:
        TAGS: mongo
        TEST_PATH: ./backend/mongo/...
    environment:
      - MONGOSTORE_URL=mongodb://mongostore:27017
      - MONGOREPLSTORE_URL=mongodb://mongostore_replicaset:27017
      - MONGOSNAP_URL=mongodb://mongosnap:27017
      - MONGOMODEL_URL=mongodb://mongomodel:27017
