services:
  jetstream:
    image: nats
    command: ["-js"]
  
  test:
    depends_on:
      - jetstream
    build:
      context: ..
      dockerfile: .docker/nats-bench.Dockerfile
      args:
        TAGS: nats
    environment:
      - JETSTREAM_URL=nats://jetstream:4222
