services:
  nats:
    image: nats

  jetstream:
    image: nats
    command: ["-js"]
  
  test:
    depends_on:
      - nats
      - jetstream
    build:
      context: ..
      dockerfile: .docker/tag-test.Dockerfile
      args:
        TAGS: nats
    environment:
      - NATS_URL=nats://nats:4222
      - JETSTREAM_URL=nats://jetstream:4222
