#!/bin/bash
set -e

generate() {
	local file=$1
	local name=$(basename $file)
	local dir=$(dirname $file)
	local dir_name=$(basename $dir)
	local short_dir_name=${dir_name#goes/}
	local out_dir=$root/api/proto/gen/$short_dir_name

	echo "Generate $file ..."

	rm -rf $out_dir/*.pb.go
	mkdir -p $out_dir
	protoc -I $root/api/proto \
		--go_out=module=github.com/modernice/goes/api/proto/gen/$short_dir_name:$out_dir $file \
		--go-grpc_out=module=github.com/modernice/goes/api/proto/gen/$short_dir_name:$out_dir $file
}

root=$(git rev-parse --show-toplevel)
proto_files=$(find $root/api/proto -name '*.proto')

proto_root=$(go list -f "{{ .Dir }}" -m github.com/modernice/goes/api/proto)

for file in $proto_files; do
	generate $file
done
